repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: check-merge-conflict
          - id: end-of-file-fixer
    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: poetry run pylint
            language: system
            types: [python]
            args: [
                    "-rn", # Only display messages
                    "-sn", # Don't display the score
                ]
